name: Development

# Controls when the action will run.
on:
  # Triggers the workflow on push events for all branches
  # Triggers the workflow on pull request events but only for the master branch
  push:
    branches: [ Development ]
  pull_request:
    branches: [ Development ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

    - name: Set up Python
      uses: actions/setup-python@v2
    
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    
    - name: Compile target esp32doit-devkit-v1-usb
      run: platformio run --environment esp32doit-devkit-v1-usb

    - name: Compile target ttgo-t-display-usb
      run: platformio run --environment ttgo-t-display-usb

    - name: Perform static checks on target esp32doit-devkit-v1-usb
      run: platformio check --environment esp32doit-devkit-v1-usb

    - name: Perform static checks on native environment
      run: platformio check --environment test

    - name: Run tests on native environment
      run: platformio test --environment test

    - name: Set up graphviz
      uses: ts-graphviz/setup-graphviz@v1

    - name: Set up doxygen and generate documentation
      uses: mattnotmitt/doxygen-action@v1.1.0
      with:
        working-directory: './doc/doxygen'
        doxyfile-path: './Doxyfile'
