name: PlatformIO CI

# Controls when the action will run.
on:
  # Triggers the workflow on push events for all branches
  # Triggers the workflow on pull request events but only for the master branch
  push:
    branches: [ master, Development ]
  pull_request:
    branches: [ master, Development ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v1
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio
        platformio update

    - name: Run tests on native environment
      run: platformio test --environment test --without-testing

    - name: Test
      run: sudo apt-get update && sudo apt-get install gdb && gdb -x script.gdb
