name: master

# Controls when the action will run.
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  # Setup the toolchain and checkout the repository.
  setup:
    # The type of runner that the job will run on.
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job.
    steps:
    - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
    - run: echo "The name of the branch is ${{ github.ref }} and the repository is ${{ github.repository }}."
    
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

    - name: Set up Python
      uses: actions/setup-python@v2
    
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    
    - name: Create release artifcats folder
      if: github.ref_type == 'tag'
      run: |
        mkdir ${{ github.workspace }}/artifacts

  # Build all targets
  build:
    # The type of runner that the job will run on.
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix:
        environment: ["esp32doit-devkit-v1-usb", "esp32-nodemcu-usb", "az-delivery-devkit-v4-usb", "ttgo-t-display-usb"]
    steps:
    - name: Compile ${{ matrix.environment }} firmware
      run: platformio run --environment ${{ matrix.environment }}
    
    - name: Build ${{ matrix.environment }} filesystem image
      run: platformio run --environment ${{ matrix.environment }} --target buildfs

    - name: Deploy ${{ matrix.environment }}
      if: github.ref_type == 'tag'
      run: |
        mkdir ${{ github.workspace }}/artifacts/${{ matrix.environment }}
        cp ${{ github.workspace }}/.pio/build/${{ matrix.environment }}/firmware.bin ${{ github.workspace }}/artifacts/${{ matrix.environment }}
        cp ${{ github.workspace }}/.pio/build/${{ matrix.environment }}/spiffs.bin ${{ github.workspace }}/artifacts/${{ matrix.environment }}      

  # Static checks
  checks:
    # The type of runner that the job will run on.
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: Perform static checks on target esp32doit-devkit-v1-usb
      run: platformio check --environment esp32doit-devkit-v1-usb

    - name: Perform static checks on native environment
      run: platformio check --environment test

    - name: Run tests on native environment
      run: platformio test --environment test

  # Build documentation
  docs:
    # The type of runner that the job will run on.
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: Set up graphviz
      uses: ts-graphviz/setup-graphviz@v1

    - name: Set up doxygen and generate documentation
      uses: mattnotmitt/doxygen-action@v1.1.0
      with:
        working-directory: './doc/doxygen'
        doxyfile-path: './Doxyfile'

  # Deploy release artifacts
  deploy:
    # The type of runner that the job will run on.
    runs-on: ubuntu-latest
    needs: [setup, build, checks, docs]
    steps:
    - name: Deploy release artifacts
      uses: actions/upload-artifact@v2
      if: github.ref_type == 'tag'
      with:
        path: ${{ github.workspace }}/artifacts
