name: PlatformIO CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio
    - name: Compile target esp32doit-devkit-v1
      run: platformio run --environment esp32doit-devkit-v1
    - name: Check target esp32doit-devkit-v1
      run: platformio check --environment esp32doit-devkit-v1 --skip-packages
    - name: Run tests on native platform
      run: platformio test --environment native
    - name: Set up graphviz
      uses: ts-graphviz/setup-graphviz@v1
    - name: Set up doxygen and generate documentation
      uses: mattnotmitt/doxygen-action@v1.1.0
      with:
        working-directory: './doc/doxygen'
        doxyfile-path: './doc/doxygen/Doxyfile'
